import pandas as pd
import numpy as np
# ^^^ pyforest auto-imports - don't write above this line
# Importing convetion

In [3]:
import pandas as pd
import numpy as np

In [4]:
!pip install pandas --upgrade --user

  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.3
    Uninstalling pandas-1.0.3:
      Successfully uninstalled pandas-1.0.3


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Acesso negado: 'c:\\users\\andreaguiar\\appdata\\roaming\\python\\python37\\site-packages\\~.ndas\\_libs\\algos.cp37-win_amd64.pyd'
Check the permissions.



In [2]:
pd.__version__

'1.0.4'

# What is Pandas?

Pandas can be thought as an enhanced version of numpy arrays. In this case, the rows and columns can be identified with labels instead of just simple integer indices.

There are **three** main pandas elements we **need** to understand.
1. Pandas Series
2. Pandas DataFrame
3. Index

# The Pandas Series

A pandas series is a one-dimensional (**1-D**) indexed array.

In [4]:
pd

<module 'pandas' from 'C:\\Users\\andreaguiar\\AppData\\Roaming\\Python\\Python37\\site-packages\\pandas\\__init__.py'>

In [7]:
pd.Series()

c:\programas\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


Series([], dtype: float64)

### Series from a list

In [9]:
pd.Series([5,8,3])

0    5
1    8
2    3
dtype: int64

In [10]:
pd.Series([5,8,3])[1]

8

In [17]:
x = pd.Series(['a','b','c'])
x

0    a
1    b
2    c
dtype: object

In [16]:
x[0]

'a'

In [18]:
x = pd.Series(['a', 2, 3])
x

0    a
1    2
2    3
dtype: object

In [22]:
type(x)

pandas.core.series.Series

In [24]:
type(x[0])

str

In [23]:
type(x[1])

int

In [25]:
data = pd.Series([10,23,3,43,25,136])

In [26]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

## Values and Indexes

In [28]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [29]:
range(6)

range(0, 6)

In [30]:
data.values

array([ 10,  23,   3,  43,  25, 136], dtype=int64)

In [31]:
data.max()

136

## Accessing elements 

Can be done like a numpy array

In [32]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

In [33]:
data[0]

10

In [34]:
data[4:]

4     25
5    136
dtype: int64

In [35]:
x = np.array([10,23,3,43,25,136])
x

array([ 10,  23,   3,  43,  25, 136])

In [36]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

In summary, a Pandas Series can be thought as a kind of 1-D numpy array.

### What is the difference then? Numpy array vs Pandas Series

Mostly the index notation.

Numpy arrays only have the **implicit index** associated with its location. By using a **explicit** index notation, Pandas Series are much more flexible. For example:

## Index don't need to be numbers.

In [37]:
z = pd.Series(data=[1,2,3,5,2,7], 
              index=['Andre','Matheus', 'Marcus', 'Duane','Camila', 'Pedro'])
z

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Pedro      7
dtype: int64

### Then how can I access this pandas series?

In [40]:
z['Matheus']

2

### Slicing works here too

In [43]:
z['Matheus':'Camila']

Matheus    2
Marcus     3
Duane      5
Camila     2
dtype: int64

## Indexes don't need to be in sequence

In [44]:
data = pd.Series(data=[1,2,3,4], 
                 index=[1,7,4313,19])

In [45]:
data

1       1
7       2
4313    3
19      4
dtype: int64

In [46]:
data[4313]

3

In [47]:
data[0]

KeyError: 0

### One can think of a pandas series, then, as a form of dictionary, in which the indexes are keys and the rows are the values

Let's create a pandas series from a dict.

In [49]:
data.index

Int64Index([1, 7, 4313, 19], dtype='int64')

In [48]:
data.keys()

Int64Index([1, 7, 4313, 19], dtype='int64')

In [50]:
my_dict = {'MATHEUS': 0, 
           'ANDRE':10}

In [51]:
my_dict

{'MATHEUS': 0, 'ANDRE': 10}

In [52]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [53]:
pd.Series(my_dict)

MATHEUS     0
ANDRE      10
dtype: int64

In [54]:
pd.Series([0, 10])

0     0
1    10
dtype: int64

In [55]:
my_dict = {0: 0, 1:10}
pd.Series(my_dict)

0     0
1    10
dtype: int64

In [62]:
z = pd.Series(index=['Andre','Matheus', 'Marcus', 'Duane','Camila', 'Marcus'],    
              data=[1,2,3,5,2,7])
z

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Marcus     7
dtype: int64

In [71]:
# extra: multi-index
x = pd.Series(data=[4,5,6],
          index=[pd.Series(['SP','SP','RJ']), pd.Series(['Sao Paulo','Osasco','Brooklin'])])
x['SP']

In [78]:
z = pd.Series([1,2,3,5,2,7], ['Andre','Matheus', 'Marcus', 'Duane','Camila', 'Marcus'])
z

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Marcus     7
dtype: int64

In [80]:
z['Marcus']

Marcus    3
Marcus    7
dtype: int64

# What about > 1-D?


# Pandas DataFrame


Pandas Dataframes can be thought as a generalization of **2-D** numpy arrays. However, again, they bring flexibility on both the indices and column names.

In [ ]:
pd.DataFrame()

In [ ]:
type(pd.DataFrame())

## Pandas DataFrame can be thought as a group of Pandas Series

In [90]:
data = pd.Series(index=['Andre','Matheus', 'Marcus', 'Duane','Camila', 'Yuri'],    
              data=[1,2,3,5,2,7])
data

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Yuri       7
dtype: int64

In [91]:
another_data = pd.Series(index=['Andre','Matheus', 'Marcus', 'Duane','Camila', 'Yuri'],    
              data=[80,70,75,60,65,60])
another_data

Andre      80
Matheus    70
Marcus     75
Duane      60
Camila     65
Yuri       60
dtype: int64

In [94]:
my_dict = {'nota': data,
           'peso': another_data}

In [96]:
my_dict['peso']

Andre      80
Matheus    70
Marcus     75
Duane      60
Camila     65
Yuri       60
dtype: int64

In [99]:
df = pd.DataFrame(my_dict)
df

nota  peso
Andre       1    80
Matheus     2    70
Marcus      3    75
Duane       5    60
Camila      2    65
Yuri        7    60

In [100]:
df.T

Andre  Matheus  Marcus  Duane  Camila  Yuri
nota      1        2       3      5       2     7
peso     80       70      75     60      65    60

# Create dataframe as a collection of Series

In [105]:
example_dict = {'coluna1':data, 'coluna2':another_data}
example_dict

{'coluna1': Andre      1
 Matheus    2
 Marcus     3
 Duane      5
 Camila     2
 Yuri       7
 dtype: int64,
 'coluna2': Andre      80
 Matheus    70
 Marcus     75
 Duane      60
 Camila     65
 Yuri       60
 dtype: int64}

In [106]:
example_dict['coluna1']

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Yuri       7
dtype: int64

In [107]:
example_dict['coluna2']

Andre      80
Matheus    70
Marcus     75
Duane      60
Camila     65
Yuri       60
dtype: int64

In [108]:
x = pd.DataFrame({'coluna1':data, 
                  'coluna2':another_data, 
                  'coluna3':data * 2})
x

coluna1  coluna2  coluna3
Andre          1       80        2
Matheus        2       70        4
Marcus         3       75        6
Duane          5       60       10
Camila         2       65        4
Yuri           7       60       14

## Accessing elements in a dataframe

### If you select using a column name, it will return a Pandas Series

In [114]:
x

coluna1  coluna2  coluna3
Andre          1       80        2
Matheus        2       70        4
Marcus         3       75        6
Duane          5       60       10
Camila         2       65        4
Yuri           7       60       14

In [115]:
x['coluna2']

Andre      80
Matheus    70
Marcus     75
Duane      60
Camila     65
Yuri       60
Name: coluna2, dtype: int64

### If you select using a list of column names, it will return a Pandas DataFrame

In [116]:
x[['coluna1','coluna3']]

coluna1  coluna3
Andre          1        2
Matheus        2        4
Marcus         3        6
Duane          5       10
Camila         2        4
Yuri           7       14

In [121]:
x[['coluna1']]

coluna1
Andre          1
Matheus        2
Marcus         3
Duane          5
Camila         2
Yuri           7

### Check their shapes

In [126]:
np.array([1,2,3,4,5,6]).shape

(6,)

In [123]:
x['coluna1'].shape

(6,)

In [127]:
x[['coluna1']]

coluna1
Andre          1
Matheus        2
Marcus         3
Duane          5
Camila         2
Yuri           7

In [129]:
np.random.randint(0, 10, size=(6,1))

array([[5],
       [5],
       [1],
       [0],
       [7],
       [8]])

In [128]:
x[['coluna1']].shape

(6, 1)

### Accessing more than one column at a time

In [182]:
type(x)

pandas.core.frame.DataFrame

In [187]:
['coluna1','coluna3']

['coluna1', 'coluna3']

In [186]:
x[['coluna1','coluna3']]

coluna1  coluna3
Andre        160        2
Matheus      280        4
Marcus       450        6
Duane        600       10
Camila       260        4
Yuri         840       14

### Convert a pandas series to a dataframe

In [131]:
x['coluna1']

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Yuri       7
Name: coluna1, dtype: int64

In [148]:
x.keys()

Index(['coluna1', 'coluna2', 'coluna3'], dtype='object')

In [151]:
x['coluna1'].keys()

Index(['Andre', 'Matheus', 'Marcus', 'Duane', 'Camila', 'Yuri'], dtype='object')

### Insert values into a column of your dataframe

In [156]:
x['coluna1'] * 5

Andre       5
Matheus    10
Marcus     15
Duane      25
Camila     10
Yuri       35
Name: coluna1, dtype: int64

In [160]:
my_list = [1,2,3]

In [163]:
my_list[0] = 0

In [164]:
my_list

[0, 2, 3]

In [166]:
x['coluna1']

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Yuri       7
Name: coluna1, dtype: int64

In [167]:
# input data with same length
x['coluna1'] = [3, 6, 9, 10, 3, 14]

In [176]:
x

coluna1  coluna2  coluna3
Andre        160       80        2
Matheus      280       70        4
Marcus       450       75        6
Duane        600       60       10
Camila       260       65        4
Yuri         840       60       14

In [169]:
x['coluna1'] = [3, 6, 9, 10, 3]

ValueError: Length of values does not match length of index

In [174]:
x['coluna1'] = x['coluna2'] * x['coluna3']

In [175]:
x

coluna1  coluna2  coluna3
Andre        160       80        2
Matheus      280       70        4
Marcus       450       75        6
Duane        600       60       10
Camila       260       65        4
Yuri         840       60       14

In [180]:
pd.DataFrame({'idade':[10,20,30], 'peso':[30,40,60]}, index=[44,33,1])

idade  peso
44     10    30
33     20    40
1      30    60

## So a dataframe can be thought of as a dictionary, in which keys are the column names and values are the pandas series themselves

Also, remember that Pandas Series themselves can also be thought as another dictionary (in which Indexes are the keys).

In [190]:
a = np.random.randint(0,10, (3,5))

In [191]:
a

array([[7, 7, 1, 9, 4],
       [2, 5, 9, 2, 8],
       [1, 5, 1, 5, 0]])

In [192]:
pd.DataFrame(a)

0  1  2  3  4
0  7  7  1  9  4
1  2  5  9  2  8
2  1  5  1  5  0

In [194]:
pd.DataFrame(a)[4]

0    4
1    8
2    0
Name: 4, dtype: int32

In [195]:
a = pd.DataFrame(a, columns=['a','b','c','d','e'])
a

a  b  c  d  e
0  7  7  1  9  4
1  2  5  9  2  8
2  1  5  1  5  0

In [197]:
a['e']

0    4
1    8
2    0
Name: e, dtype: int32

In [199]:
a = np.random.randint(0,10, (3,5,2))

In [201]:
a

array([[[3, 5],
        [4, 1],
        [1, 5],
        [2, 5],
        [1, 5]],

       [[8, 2],
        [1, 8],
        [8, 0],
        [7, 9],
        [5, 3]],

       [[0, 1],
        [3, 6],
        [8, 2],
        [0, 1],
        [1, 9]]])

In [200]:
pd.DataFrame(a)

ValueError: Must pass 2-d input

## From a list in 1-D

In [203]:
[1,2,3]

[1, 2, 3]

In [204]:
np.array([1,2,3])

array([1, 2, 3])

In [205]:
np.array([1,2,3]).shape

(3,)

In [209]:
pd.DataFrame(data=[1,2,3], columns=['ironhack'], index=['a','b',4])

ironhack
a         1
b         2
4         3

## From a list in > 1-D (let's remember numpy arrays here!)

In [210]:
[[1,2,3],[-5,-6,-7]]

[[1, 2, 3], [-5, -6, -7]]

In [211]:
np.array([[1,2,3],[-5,-6,-7]])

array([[ 1,  2,  3],
       [-5, -6, -7]])

In [212]:
np.array([[1,2,3],[-5,-6,-7]]).shape

(2, 3)

In [214]:
df = pd.DataFrame(data=[[1,2,3],[-5,-6,-7]], columns=['ironhack','digital_house','lewagon'])
df

ironhack  digital_house  lewagon
0         1              2        3
1        -5             -6       -7

## Math operations

In [215]:
x

coluna1  coluna2  coluna3
Andre        160       80        2
Matheus      280       70        4
Marcus       450       75        6
Duane        600       60       10
Camila       260       65        4
Yuri         840       60       14

In [216]:
x.transpose()

Andre  Matheus  Marcus  Duane  Camila  Yuri
coluna1    160      280     450    600     260   840
coluna2     80       70      75     60      65    60
coluna3      2        4       6     10       4    14

In [217]:
x.T

Andre  Matheus  Marcus  Duane  Camila  Yuri
coluna1    160      280     450    600     260   840
coluna2     80       70      75     60      65    60
coluna3      2        4       6     10       4    14

In [220]:
x

coluna1  coluna2  coluna3
Andre        160       80        2
Matheus      280       70        4
Marcus       450       75        6
Duane        600       60       10
Camila       260       65        4
Yuri         840       60       14

In [224]:
x.mean()

coluna1    431.666667
coluna2     68.333333
coluna3      6.666667
dtype: float64

In [221]:
x.mean(axis=1)

Andre       80.666667
Matheus    118.000000
Marcus     177.000000
Duane      223.333333
Camila     109.666667
Yuri       304.666667
dtype: float64

In [227]:
x.std()

coluna1    253.646736
coluna2      8.164966
coluna3      4.501851
dtype: float64

In [226]:
x.std(axis=1)

Andre       79.002110
Matheus    144.124946
Marcus     238.928860
Duane      327.159492
Camila     133.717364
Yuri       464.182435
dtype: float64

In [228]:
x.describe()

coluna1    coluna2    coluna3
count    6.000000   6.000000   6.000000
mean   431.666667  68.333333   6.666667
std    253.646736   8.164966   4.501851
min    160.000000  60.000000   2.000000
25%    265.000000  61.250000   4.000000
50%    365.000000  67.500000   5.000000
75%    562.500000  73.750000   9.000000
max    840.000000  80.000000  14.000000

In [243]:
x.style.highlight_min()

In [242]:
x.style.background_gradient(cmap='Greens', axis=0)

In [235]:
x.sort_values(by='coluna2')

coluna1  coluna2  coluna3
Duane        600       60       10
Yuri         840       60       14
Camila       260       65        4
Matheus      280       70        4
Marcus       450       75        6
Andre        160       80        2

# Pandas Index

In [244]:
pd.Index([1,2,3])

Int64Index([1, 2, 3], dtype='int64')

In [248]:
data

Andre      1
Matheus    2
Marcus     3
Duane      5
Camila     2
Yuri       7
dtype: int64

In [249]:
data.index

Index(['Andre', 'Matheus', 'Marcus', 'Duane', 'Camila', 'Yuri'], dtype='object')

In [250]:
data.index.values

array(['Andre', 'Matheus', 'Marcus', 'Duane', 'Camila', 'Yuri'],
      dtype=object)

In [251]:
pd.DataFrame(data=[1,2,3], 
             index=[693, 331, 'andre'], 
             columns=['colname'])

colname
693          1
331          2
andre        3

## Extra:  Save to html

In [253]:
y = x.style

In [255]:
text_file = open("index.html", "w")
text_file.write(x.to_html())
text_file.close()
