In [338]:
import pandas as pd
import numpy as np

In [2]:
pd.Series(data=[1,2,3,'andre','matheus',[1,2,3]], 
          index=[5,4,3,2,1,'SP'])

5             1
4             2
3             3
2         andre
1       matheus
SP    [1, 2, 3]
dtype: object

In [3]:
x = pd.DataFrame({'age': [1,4,7], 
                   'weight':[8,3,1]})
x

age  weight
0    1       8
1    4       3
2    7       1

In [4]:
x.sample(n=2)

age  weight
0    1       8
1    4       3

In [5]:
x.head(1)

age  weight
0    1       8

In [6]:
x['weight']

0    8
1    3
2    1
Name: weight, dtype: int64

In [7]:
x[['age','weight']]

age  weight
0    1       8
1    4       3
2    7       1

In [8]:
x.describe()

age    weight
count  3.0  3.000000
mean   4.0  4.000000
std    3.0  3.605551
min    1.0  1.000000
25%    2.5  2.000000
50%    4.0  3.000000
75%    5.5  5.500000
max    7.0  8.000000

# Data Manipulation - PART 1

In [9]:
!pwd

/c/Users/andreaguiar/Desktop/usr/dev/ironhack/ft202006/classes/week2/5_Data_Manipulation_Part1


In [10]:
# !cd

In [11]:
# data = pd.read_csv('../4_Pandas_Import_Export/data/vehicles.csv')
data = pd.read_csv('vehicles/vehicles.csv')

In [12]:
data.head()

Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [13]:
data.shape
# (nrows, ncolumns)

(35952, 15)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Make                     35952 non-null  object 
 1   Model                    35952 non-null  object 
 2   Year                     35952 non-null  int64  
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object 
 6   Drivetrain               35952 non-null  object 
 7   Vehicle Class            35952 non-null  object 
 8   Fuel Type                35952 non-null  object 
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64  
 11  Highway MPG              35952 non-null  int64  
 12  Combined MPG             35952 non-null  int64  
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year        

In [15]:
y = pd.DataFrame([1,2,3], index=['Andre','Bruno','Eduardo'])

In [16]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Andre to Eduardo
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 48.0+ bytes


In [18]:
data.head()

Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

## Checking the dataframe column names

In [21]:
data

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   
35951             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   
35951        3.0     Manual 5-spd  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   
35951                  Two Seaters   Premium           9.417429        32   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 15 columns]

In [24]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [25]:
data.columns[-1]

'Fuel Cost/Year'

In [28]:
for col in data.columns:
    print(col.lower())

make
model
year
engine displacement
cylinders
transmission
drivetrain
vehicle class
fuel type
fuel barrels/year
city mpg
highway mpg
combined mpg
co2 emission grams/mile
fuel cost/year


In [37]:
data.columns = [col.lower().strip().replace(' ','_').replace('/','_') for col in data.columns]

In [38]:
data.head()

make                model  year  engine_displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   cylinders     transmission        drivetrain                vehicle_class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  fuel_type  fuel_barrels_year  city_mpg  highway_mpg  combined_mpg  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   co2_emission_grams_mile  fuel_cost_year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [39]:
data.dtypes

make                        object
model                       object
year                         int64
engine_displacement        float64
cylinders                  float64
transmission                object
drivetrain                  object
vehicle_class               object
fuel_type                   object
fuel_barrels_year          float64
city_mpg                     int64
highway_mpg                  int64
combined_mpg                 int64
co2_emission_grams_mile    float64
fuel_cost_year               int64
dtype: object

In [40]:
type(data.dtypes)

pandas.core.series.Series

In [43]:
data.dtypes['transmission']

dtype('O')

In [42]:
data.dtypes['transmission'] == 'object'

True

## Selecting columns based on types: `.select_dtypes`

In [51]:
data.select_dtypes('object')

make                model     transmission  \
0            AM General    DJ Po Vehicle 2WD  Automatic 3-spd   
1            AM General     FJ8c Post Office  Automatic 3-spd   
2            AM General  Post Office DJ5 2WD  Automatic 3-spd   
3            AM General  Post Office DJ8 2WD  Automatic 3-spd   
4      ASC Incorporated                  GNX  Automatic 4-spd   
...                 ...                  ...              ...   
35947             smart         fortwo coupe        Auto(AM5)   
35948             smart         fortwo coupe        Auto(AM5)   
35949             smart         fortwo coupe        Auto(AM5)   
35950             smart         fortwo coupe        Auto(AM6)   
35951             smart         fortwo coupe     Manual 5-spd   

             drivetrain                vehicle_class fuel_type  
0         2-Wheel Drive  Special Purpose Vehicle 2WD   Regular  
1         2-Wheel Drive  Special Purpose Vehicle 2WD   Regular  
2      Rear-Wheel Drive  Special Purpose Vehicle 2WD   Regular  
3      Rear-Wheel Drive  Special Purpose Vehicle 2WD   Regular  
4      Rear-Wheel Drive                 Midsize Cars   Premium  
...                 ...                          ...       ...  
35947  Rear-Wheel Drive                  Two Seaters   Premium  
35948  Rear-Wheel Drive                  Two Seaters   Premium  
35949  Rear-Wheel Drive                  Two Seaters   Premium  
35950  Rear-Wheel Drive                  Two Seaters   Premium  
35951  Rear-Wheel Drive                  Two Seaters   Premium  

[35952 rows x 6 columns]

In [50]:
data.select_dtypes(exclude='object')

year  engine_displacement  cylinders  fuel_barrels_year  city_mpg  \
0      1984                  2.5        4.0          19.388824        18   
1      1984                  4.2        6.0          25.354615        13   
2      1985                  2.5        4.0          20.600625        16   
3      1985                  4.2        6.0          25.354615        13   
4      1987                  3.8        6.0          20.600625        14   
...     ...                  ...        ...                ...       ...   
35947  2013                  1.0        3.0           9.155833        34   
35948  2014                  1.0        3.0           9.155833        34   
35949  2015                  1.0        3.0           9.155833        34   
35950  2016                  0.9        3.0           9.155833        34   
35951  2016                  0.9        3.0           9.417429        32   

       highway_mpg  combined_mpg  co2_emission_grams_mile  fuel_cost_year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  
35951           39            35               255.000000            1150  

[35952 rows x 9 columns]

In [53]:
data = pd.read_csv('vehicles/vehicles.csv')
data.head()

Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

## Altering data type: `.astype()`

In [55]:
data.head(1)

Make              Model  Year  Engine Displacement  Cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950

In [64]:
data['Cylinders'].astype(int)

0        4
1        6
2        4
3        6
4        6
        ..
35947    3
35948    3
35949    3
35950    3
35951    3
Name: Cylinders, Length: 35952, dtype: int32

In [61]:
data['Cylinders'] = data['Cylinders'].astype(int)

In [62]:
data['Cylinders']

0        4
1        6
2        4
3        6
4        6
        ..
35947    3
35948    3
35949    3
35950    3
35951    3
Name: Cylinders, Length: 35952, dtype: int32

In [66]:
data.head(1)

Make              Model  Year  Engine Displacement  Cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5          4   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950

In [68]:
data.dtypes

Make                        object
Model                       object
Year                         int64
Engine Displacement        float64
Cylinders                    int32
Transmission                object
Drivetrain                  object
Vehicle Class               object
Fuel Type                   object
Fuel Barrels/Year          float64
City MPG                     int64
Highway MPG                  int64
Combined MPG                 int64
CO2 Emission Grams/Mile    float64
Fuel Cost/Year               int64
dtype: object

In [72]:
data.dtypes['Combined MPG'] == 'int64'

True

In [77]:
data = pd.read_csv('vehicles/vehicles.csv')

renamed_cols = []

for colname in data.columns:
    if data.dtypes[colname] == 'object':
        renamed_cols.append('str_' + colname.lower())
    elif data.dtypes[colname] == 'int64':
        renamed_cols.append('qtd_' + colname.lower())
    elif data.dtypes[colname] == 'float64':
        renamed_cols.append('vlr_' + colname.lower())

In [79]:
data.columns = renamed_cols

In [80]:
data.head()

str_make            str_model  qtd_year  vlr_engine displacement  \
0        AM General    DJ Po Vehicle 2WD      1984                      2.5   
1        AM General     FJ8c Post Office      1984                      4.2   
2        AM General  Post Office DJ5 2WD      1985                      2.5   
3        AM General  Post Office DJ8 2WD      1985                      4.2   
4  ASC Incorporated                  GNX      1987                      3.8   

   vlr_cylinders str_transmission    str_drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   

             str_vehicle class str_fuel type  vlr_fuel barrels/year  \
0  Special Purpose Vehicle 2WD       Regular              19.388824   
1  Special Purpose Vehicle 2WD       Regular              25.354615   
2  Special Purpose Vehicle 2WD       Regular              20.600625   
3  Special Purpose Vehicle 2WD       Regular              25.354615   
4                 Midsize Cars       Premium              20.600625   

   qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
0            18               17                17   
1            13               13                13   
2            16               17                16   
3            13               13                13   
4            14               21                16   

   vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                   522.764706                1950  
1                   683.615385                2550  
2                   555.437500                2100  
3                   683.615385                2550  
4                   555.437500                2550

## NaN - Not a Number (missing)

In [81]:
np.nan

nan

In [86]:
type(np.nan)

float

In [93]:
pd.DataFrame([3, 4, np.nan, 'a'], columns=['col'])

col
0    3
1    4
2  NaN
3    a

In [85]:
pd.DataFrame(['a','s', 'c', np.nan, 1], columns=['col'])

col
0    a
1    s
2    c
3  NaN
4    1

In [ ]:
pd.DataFrame([1,2, 3, np.nan])

In [99]:
9 == 9

True

In [101]:
np.nan != np.nan

True

In [102]:
9 != 9

False

In [120]:
x = pd.DataFrame([1,2, np.nan, 3, ])

In [121]:
x

0
0  1.0
1  2.0
2  NaN
3  3.0

In [122]:
# verifies which cells are NaN
x.isna()

0
0  False
1  False
2   True
3  False

In [123]:
# throw away missing
x.dropna()

0
0  1.0
1  2.0
3  3.0

## Accessing dataframes

> * `.iloc`
- Serve pra você selecionar uma parte do dataframe especificando o valor do índice (**implícito**) de linhas e colunas. 

> * `.loc`
- Serve pra você selecionar uma parte do dataframe especificando o **NOME** de linhas e colunas.

In [124]:
data.head(1)

str_make          str_model  qtd_year  vlr_engine displacement  \
0  AM General  DJ Po Vehicle 2WD      1984                      2.5   

   vlr_cylinders str_transmission str_drivetrain            str_vehicle class  \
0            4.0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   

  str_fuel type  vlr_fuel barrels/year  qtd_city mpg  qtd_highway mpg  \
0       Regular              19.388824            18               17   

   qtd_combined mpg  vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                17                   522.764706                1950

In [125]:
data['qtd_year']

0        1984
1        1984
2        1985
3        1985
4        1987
         ... 
35947    2013
35948    2014
35949    2015
35950    2016
35951    2016
Name: qtd_year, Length: 35952, dtype: int64

In [126]:
data[['vlr_cylinders', 'str_model']]

vlr_cylinders            str_model
0                4.0    DJ Po Vehicle 2WD
1                6.0     FJ8c Post Office
2                4.0  Post Office DJ5 2WD
3                6.0  Post Office DJ8 2WD
4                6.0                  GNX
...              ...                  ...
35947            3.0         fortwo coupe
35948            3.0         fortwo coupe
35949            3.0         fortwo coupe
35950            3.0         fortwo coupe
35951            3.0         fortwo coupe

[35952 rows x 2 columns]

## Loc

In [128]:
data.loc[[0,1,3], ['qtd_year', 'vlr_cylinders']]

qtd_year  vlr_cylinders
0      1984            4.0
1      1984            6.0
3      1985            6.0

In [129]:
data.loc[0:10, ['qtd_year', 'vlr_cylinders']]

qtd_year  vlr_cylinders
0       1984            4.0
1       1984            6.0
2       1985            4.0
3       1985            6.0
4       1987            6.0
5       1997            4.0
6       1997            4.0
7       1997            6.0
8       1998            4.0
9       1998            4.0
10      1998            6.0

In [134]:
data.loc[:, ['qtd_year','vlr_cylinders']]

qtd_year  vlr_cylinders
0          1984            4.0
1          1984            6.0
2          1985            4.0
3          1985            6.0
4          1987            6.0
...         ...            ...
35947      2013            3.0
35948      2014            3.0
35949      2015            3.0
35950      2016            3.0
35951      2016            3.0

[35952 rows x 2 columns]

In [135]:
data.loc[0:10, :]

str_make            str_model  qtd_year  vlr_engine displacement  \
0         AM General    DJ Po Vehicle 2WD      1984                      2.5   
1         AM General     FJ8c Post Office      1984                      4.2   
2         AM General  Post Office DJ5 2WD      1985                      2.5   
3         AM General  Post Office DJ8 2WD      1985                      4.2   
4   ASC Incorporated                  GNX      1987                      3.8   
5              Acura          2.2CL/3.0CL      1997                      2.2   
6              Acura          2.2CL/3.0CL      1997                      2.2   
7              Acura          2.2CL/3.0CL      1997                      3.0   
8              Acura          2.3CL/3.0CL      1998                      2.3   
9              Acura          2.3CL/3.0CL      1998                      2.3   
10             Acura          2.3CL/3.0CL      1998                      3.0   

    vlr_cylinders str_transmission     str_drivetrain  \
0             4.0  Automatic 3-spd      2-Wheel Drive   
1             6.0  Automatic 3-spd      2-Wheel Drive   
2             4.0  Automatic 3-spd   Rear-Wheel Drive   
3             6.0  Automatic 3-spd   Rear-Wheel Drive   
4             6.0  Automatic 4-spd   Rear-Wheel Drive   
5             4.0  Automatic 4-spd  Front-Wheel Drive   
6             4.0     Manual 5-spd  Front-Wheel Drive   
7             6.0  Automatic 4-spd  Front-Wheel Drive   
8             4.0  Automatic 4-spd  Front-Wheel Drive   
9             4.0     Manual 5-spd  Front-Wheel Drive   
10            6.0  Automatic 4-spd  Front-Wheel Drive   

              str_vehicle class str_fuel type  vlr_fuel barrels/year  \
0   Special Purpose Vehicle 2WD       Regular              19.388824   
1   Special Purpose Vehicle 2WD       Regular              25.354615   
2   Special Purpose Vehicle 2WD       Regular              20.600625   
3   Special Purpose Vehicle 2WD       Regular              25.354615   
4                  Midsize Cars       Premium              20.600625   
5               Subcompact Cars       Regular              14.982273   
6               Subcompact Cars       Regular              13.733750   
7               Subcompact Cars       Regular              16.480500   
8               Subcompact Cars       Regular              14.982273   
9               Subcompact Cars       Regular              13.733750   
10              Subcompact Cars       Regular              16.480500   

    qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
0             18               17                17   
1             13               13                13   
2             16               17                16   
3             13               13                13   
4             14               21                16   
5             20               26                22   
6             22               28                24   
7             18               26                20   
8             19               27                22   
9             21               29                24   
10            17               26                20   

    vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                    522.764706                1950  
1                    683.615385                2550  
2                    555.437500                2100  
3                    683.615385                2550  
4                    555.437500                2550  
5                    403.954545                1500  
6                    370.291667                1400  
7                    444.350000                1650  
8                    403.954545                1500  
9                    370.291667                1400  
10                   444.350000                1650

In [136]:
data.loc[0:10]

str_make            str_model  qtd_year  vlr_engine displacement  \
0         AM General    DJ Po Vehicle 2WD      1984                      2.5   
1         AM General     FJ8c Post Office      1984                      4.2   
2         AM General  Post Office DJ5 2WD      1985                      2.5   
3         AM General  Post Office DJ8 2WD      1985                      4.2   
4   ASC Incorporated                  GNX      1987                      3.8   
5              Acura          2.2CL/3.0CL      1997                      2.2   
6              Acura          2.2CL/3.0CL      1997                      2.2   
7              Acura          2.2CL/3.0CL      1997                      3.0   
8              Acura          2.3CL/3.0CL      1998                      2.3   
9              Acura          2.3CL/3.0CL      1998                      2.3   
10             Acura          2.3CL/3.0CL      1998                      3.0   

    vlr_cylinders str_transmission     str_drivetrain  \
0             4.0  Automatic 3-spd      2-Wheel Drive   
1             6.0  Automatic 3-spd      2-Wheel Drive   
2             4.0  Automatic 3-spd   Rear-Wheel Drive   
3             6.0  Automatic 3-spd   Rear-Wheel Drive   
4             6.0  Automatic 4-spd   Rear-Wheel Drive   
5             4.0  Automatic 4-spd  Front-Wheel Drive   
6             4.0     Manual 5-spd  Front-Wheel Drive   
7             6.0  Automatic 4-spd  Front-Wheel Drive   
8             4.0  Automatic 4-spd  Front-Wheel Drive   
9             4.0     Manual 5-spd  Front-Wheel Drive   
10            6.0  Automatic 4-spd  Front-Wheel Drive   

              str_vehicle class str_fuel type  vlr_fuel barrels/year  \
0   Special Purpose Vehicle 2WD       Regular              19.388824   
1   Special Purpose Vehicle 2WD       Regular              25.354615   
2   Special Purpose Vehicle 2WD       Regular              20.600625   
3   Special Purpose Vehicle 2WD       Regular              25.354615   
4                  Midsize Cars       Premium              20.600625   
5               Subcompact Cars       Regular              14.982273   
6               Subcompact Cars       Regular              13.733750   
7               Subcompact Cars       Regular              16.480500   
8               Subcompact Cars       Regular              14.982273   
9               Subcompact Cars       Regular              13.733750   
10              Subcompact Cars       Regular              16.480500   

    qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
0             18               17                17   
1             13               13                13   
2             16               17                16   
3             13               13                13   
4             14               21                16   
5             20               26                22   
6             22               28                24   
7             18               26                20   
8             19               27                22   
9             21               29                24   
10            17               26                20   

    vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                    522.764706                1950  
1                    683.615385                2550  
2                    555.437500                2100  
3                    683.615385                2550  
4                    555.437500                2550  
5                    403.954545                1500  
6                    370.291667                1400  
7                    444.350000                1650  
8                    403.954545                1500  
9                    370.291667                1400  
10                   444.350000                1650

In [139]:
x = data.sample(10)

In [155]:
x

str_make       str_model  qtd_year  vlr_engine displacement  \
9967           Dodge       Dart Aero      2016                      1.4   
13583           Ford         Mustang      1999                      3.8   
30108    Rolls-Royce          Wraith      2017                      6.6   
15057            GMC  K15 Pickup 4WD      1988                      6.2   
12048           Ford        Edge AWD      2015                      2.0   
7909       Chevrolet     Venture FWD      2004                      3.4   
27104         Nissan       Truck 2WD      1994                      2.4   
23621  Mercedes-Benz     C350 4matic      2007                      3.5   
24317  Mercedes-Benz     S550 4matic      2012                      4.7   
29368        Porsche             968      1992                      3.0   

       vlr_cylinders str_transmission              str_drivetrain  \
9967             4.0        Auto(AM6)           Front-Wheel Drive   
13583            6.0  Automatic 4-spd            Rear-Wheel Drive   
30108           12.0   Automatic (S8)            Rear-Wheel Drive   
15057            8.0     Manual 4-spd  4-Wheel or All-Wheel Drive   
12048            4.0   Automatic (S6)             All-Wheel Drive   
7909             6.0  Automatic 4-spd           Front-Wheel Drive   
27104            4.0     Manual 5-spd            Rear-Wheel Drive   
23621            6.0  Automatic 5-spd  4-Wheel or All-Wheel Drive   
24317            8.0  Automatic 7-spd               4-Wheel Drive   
29368            4.0   Automatic (S4)            Rear-Wheel Drive   

                     str_vehicle class str_fuel type  vlr_fuel barrels/year  \
9967                      Midsize Cars       Premium              10.300313   
13583                  Subcompact Cars       Regular              16.480500   
30108                     Midsize Cars       Premium              21.974000   
15057           Standard Pickup Trucks        Diesel              23.886563   
12048  Small Sport Utility Vehicle 4WD       Regular              14.330870   
7909                     Minivan - 2WD       Regular              16.480500   
27104              Small Pickup Trucks       Premium              14.982273   
23621                     Compact Cars       Premium              17.347895   
24317                       Large Cars       Premium              18.311667   
29368                      Two Seaters       Premium              19.388824   

       qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
9967             28               40                32   
13583            17               25                20   
30108            12               19                15   
15057            16               17                16   
12048            20               28                23   
7909             17               24                20   
27104            20               24                22   
23621            17               22                19   
24317            15               24                18   
29368            15               23                17   

       vlr_co2 emission grams/mile  qtd_fuel cost/year  
9967                    275.000000                1250  
13583                   444.350000                1650  
30108                   604.000000                2700  
15057                   636.250000                2250  
12048                   388.000000                1450  
7909                    444.350000                1650  
27104                   403.954545                1850  
23621                   467.736842                2150  
24317                   493.722222                2250  
29368                   522.764706                2400

In [156]:
x.index

Int64Index([9967, 13583, 30108, 15057, 12048, 7909, 27104, 23621, 24317,
            29368],
           dtype='int64')

In [143]:
x.head(2)

str_make  str_model  qtd_year  vlr_engine displacement  vlr_cylinders  \
9967     Dodge  Dart Aero      2016                      1.4            4.0   
13583     Ford    Mustang      1999                      3.8            6.0   

      str_transmission     str_drivetrain str_vehicle class str_fuel type  \
9967         Auto(AM6)  Front-Wheel Drive      Midsize Cars       Premium   
13583  Automatic 4-spd   Rear-Wheel Drive   Subcompact Cars       Regular   

       vlr_fuel barrels/year  qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
9967               10.300313            28               40                32   
13583              16.480500            17               25                20   

       vlr_co2 emission grams/mile  qtd_fuel cost/year  
9967                        275.00                1250  
13583                       444.35                1650

In [141]:
x.loc[[9967, 13583], ['qtd_year','vlr_cylinders']]

qtd_year  vlr_cylinders
9967       2016            4.0
13583      1999            6.0

In [147]:
x.iloc[[0,1],[2,4]]

qtd_year  vlr_cylinders
9967       2016            4.0
13583      1999            6.0

In [149]:
y = pd.DataFrame([1,2,3], index=['SP','SP','RJ'])

In [154]:
y.loc['SP']

0
SP  1
SP  2

In [159]:
# data.loc[:, 'qtd_year'] vs data['qtd_year']

str_make            str_model  qtd_year  \
0            AM General    DJ Po Vehicle 2WD      1984   
1            AM General     FJ8c Post Office      1984   
2            AM General  Post Office DJ5 2WD      1985   
3            AM General  Post Office DJ8 2WD      1985   
4      ASC Incorporated                  GNX      1987   
...                 ...                  ...       ...   
35947             smart         fortwo coupe      2013   
35948             smart         fortwo coupe      2014   
35949             smart         fortwo coupe      2015   
35950             smart         fortwo coupe      2016   
35951             smart         fortwo coupe      2016   

       vlr_engine displacement  vlr_cylinders str_transmission  \
0                          2.5            4.0  Automatic 3-spd   
1                          4.2            6.0  Automatic 3-spd   
2                          2.5            4.0  Automatic 3-spd   
3                          4.2            6.0  Automatic 3-spd   
4                          3.8            6.0  Automatic 4-spd   
...                        ...            ...              ...   
35947                      1.0            3.0        Auto(AM5)   
35948                      1.0            3.0        Auto(AM5)   
35949                      1.0            3.0        Auto(AM5)   
35950                      0.9            3.0        Auto(AM6)   
35951                      0.9            3.0     Manual 5-spd   

         str_drivetrain            str_vehicle class str_fuel type  \
0         2-Wheel Drive  Special Purpose Vehicle 2WD       Regular   
1         2-Wheel Drive  Special Purpose Vehicle 2WD       Regular   
2      Rear-Wheel Drive  Special Purpose Vehicle 2WD       Regular   
3      Rear-Wheel Drive  Special Purpose Vehicle 2WD       Regular   
4      Rear-Wheel Drive                 Midsize Cars       Premium   
...                 ...                          ...           ...   
35947  Rear-Wheel Drive                  Two Seaters       Premium   
35948  Rear-Wheel Drive                  Two Seaters       Premium   
35949  Rear-Wheel Drive                  Two Seaters       Premium   
35950  Rear-Wheel Drive                  Two Seaters       Premium   
35951  Rear-Wheel Drive                  Two Seaters       Premium   

       vlr_fuel barrels/year  qtd_city mpg  qtd_highway mpg  qtd_combined mpg  \
0                  19.388824            18               17                17   
1                  25.354615            13               13                13   
2                  20.600625            16               17                16   
3                  25.354615            13               13                13   
4                  20.600625            14               21                16   
...                      ...           ...              ...               ...   
35947               9.155833            34               38                36   
35948               9.155833            34               38                36   
35949               9.155833            34               38                36   
35950               9.155833            34               39                36   
35951               9.417429            32               39                35   

       vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                       522.764706                1950  
1                       683.615385                2550  
2                       555.437500                2100  
3                       683.615385                2550  
4                       555.437500                2550  
...                            ...                 ...  
35947                   244.000000                1100  
35948                   243.000000                1100  
35949                   244.000000                1100  
35950                   246.000000                1100  
35951                   255.000000                1150  

[35952 rows x 15 columns]

# Rename columns 
>    - Rename some columns
>    - Rename all columns
>    - The `Inplace` clause

In [ ]:
# data.columns = ['uma_unica_coluna'] # error!!

In [160]:
data.head(1)

str_make          str_model  qtd_year  vlr_engine displacement  \
0  AM General  DJ Po Vehicle 2WD      1984                      2.5   

   vlr_cylinders str_transmission str_drivetrain            str_vehicle class  \
0            4.0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   

  str_fuel type  vlr_fuel barrels/year  qtd_city mpg  qtd_highway mpg  \
0       Regular              19.388824            18               17   

   qtd_combined mpg  vlr_co2 emission grams/mile  qtd_fuel cost/year  
0                17                   522.764706                1950

In [161]:
data.columns

Index(['str_make', 'str_model', 'qtd_year', 'vlr_engine displacement',
       'vlr_cylinders', 'str_transmission', 'str_drivetrain',
       'str_vehicle class', 'str_fuel type', 'vlr_fuel barrels/year',
       'qtd_city mpg', 'qtd_highway mpg', 'qtd_combined mpg',
       'vlr_co2 emission grams/mile', 'qtd_fuel cost/year'],
      dtype='object')

In [170]:
data.rename(columns={'str_make' : 'str_manufacturer'}, inplace=True)

In [172]:
data.rename({'vlr_engine displacement': 'vlr_engine_displacement',
             'str_vehicle class': 'str_vehicle_class'}, 
            axis=1, 
            inplace=True)

In [174]:
data = data.rename({'str_fuel type': 'str_fuel_type'}, axis=1)

In [ ]:
data_renamed = data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'})

# this is only printing on screen

In [ ]:
data.head(2)
# the column names did not change.

In [ ]:
data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'}, inplace=True)

Two options:
> 1. store it again on the variable `data`: 

`data = data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'})`
> 2. Use the inplace argument `inplace =  True` to change the values within the dataframe automatically

`data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'}, inplace=True)`
    

In [176]:
# using rename and storing the results in a variable
renamed_data = data.rename(columns={'Make':'Manufacturer', 'Year':'ANO'})


In [178]:
# substituting the .columns attribute of the dataframe

cols = ['Manufacturer','Model','Year','Displacement',
        'Cylinders','Transmission','Drivetrain',
        'Vehicle Class','Fuel Type','Fuel Barrels/Year',
        'City MPG','Highway MPG','Combined MPG',
        'CO2 Emission Grams/Mile','Fuel Cost/Year']

data.columns = cols
data.head(2)

Manufacturer              Model  Year  Displacement  Cylinders  \
0   AM General  DJ Po Vehicle 2WD  1984           2.5        4.0   
1   AM General   FJ8c Post Office  1984           4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

# Change ORDER
>    - Remember you always pass a list to select from a dataframe

Just select the columns in a different order and overwrite the previous dataframe

In [179]:
# substituting the .columns attribute of the dataframe

cols = ['Fuel Cost/Year', 'Manufacturer','Model','Year','Displacement',
        'Cylinders','Transmission','Drivetrain',
        'Vehicle Class','Fuel Type','Fuel Barrels/Year',
        'City MPG','Highway MPG','Combined MPG',
        'CO2 Emission Grams/Mile']

data.columns = cols
data.head(2)

Fuel Cost/Year       Manufacturer  Model  Year  Displacement  \
0     AM General  DJ Po Vehicle 2WD   1984   2.5           4.0   
1     AM General   FJ8c Post Office   1984   4.2           6.0   

         Cylinders   Transmission                   Drivetrain Vehicle Class  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD       Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD       Regular   

   Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0  19.388824                 18        17           17    522.764706   
1  25.354615                 13        13           13    683.615385   

   CO2 Emission Grams/Mile  
0                     1950  
1                     2550

In [183]:
data.loc[:, ['Manufacturer','Model']].head(2)

Manufacturer  Model
0  DJ Po Vehicle 2WD   1984
1   FJ8c Post Office   1984

In [184]:
data.loc[:, ['Model', 'Manufacturer']].head(2)

Model       Manufacturer
0   1984  DJ Po Vehicle 2WD
1   1984   FJ8c Post Office

In [186]:
# data['Year','Manufacturer'] # WRONG - not a list, you passed a string.

column_order = ['Combined MPG', 'Year','Manufacturer',
                'Model','Vehicle Class',
                'Transmission','Drivetrain','Fuel Type',
                'Cylinders','Displacement','Fuel Barrels/Year',
                'City MPG','Highway MPG',
                'CO2 Emission Grams/Mile','Fuel Cost/Year']

data = data.loc[:, column_order]
data

Combined MPG  Year         Manufacturer  Model Vehicle Class  \
0        522.764706   2.5    DJ Po Vehicle 2WD   1984       Regular   
1        683.615385   4.2     FJ8c Post Office   1984       Regular   
2        555.437500   2.5  Post Office DJ5 2WD   1985       Regular   
3        683.615385   4.2  Post Office DJ8 2WD   1985       Regular   
4        555.437500   3.8                  GNX   1987       Premium   
...             ...   ...                  ...    ...           ...   
35947    244.000000   1.0         fortwo coupe   2013       Premium   
35948    243.000000   1.0         fortwo coupe   2014       Premium   
35949    244.000000   1.0         fortwo coupe   2015       Premium   
35950    246.000000   0.9         fortwo coupe   2016       Premium   
35951    255.000000   0.9         fortwo coupe   2016       Premium   

           Transmission                   Drivetrain  Fuel Type  \
0         2-Wheel Drive  Special Purpose Vehicle 2WD  19.388824   
1         2-Wheel Drive  Special Purpose Vehicle 2WD  25.354615   
2      Rear-Wheel Drive  Special Purpose Vehicle 2WD  20.600625   
3      Rear-Wheel Drive  Special Purpose Vehicle 2WD  25.354615   
4      Rear-Wheel Drive                 Midsize Cars  20.600625   
...                 ...                          ...        ...   
35947  Rear-Wheel Drive                  Two Seaters   9.155833   
35948  Rear-Wheel Drive                  Two Seaters   9.155833   
35949  Rear-Wheel Drive                  Two Seaters   9.155833   
35950  Rear-Wheel Drive                  Two Seaters   9.155833   
35951  Rear-Wheel Drive                  Two Seaters   9.417429   

             Cylinders  Displacement  Fuel Barrels/Year  City MPG  \
0      Automatic 3-spd           4.0                 18        17   
1      Automatic 3-spd           6.0                 13        13   
2      Automatic 3-spd           4.0                 16        17   
3      Automatic 3-spd           6.0                 13        13   
4      Automatic 4-spd           6.0                 14        21   
...                ...           ...                ...       ...   
35947        Auto(AM5)           3.0                 34        38   
35948        Auto(AM5)           3.0                 34        38   
35949        Auto(AM5)           3.0                 34        38   
35950        Auto(AM6)           3.0                 34        39   
35951     Manual 5-spd           3.0                 32        39   

       Highway MPG  CO2 Emission Grams/Mile    Fuel Cost/Year  
0               17                     1950        AM General  
1               13                     2550        AM General  
2               16                     2100        AM General  
3               13                     2550        AM General  
4               16                     2550  ASC Incorporated  
...            ...                      ...               ...  
35947           36                     1100             smart  
35948           36                     1100             smart  
35949           36                     1100             smart  
35950           36                     1100             smart  
35951           35                     1150             smart  

[35952 rows x 15 columns]

# Filter records
>    - masks 
>    - query

This is really important for data wrangling.

In [187]:
data = pd.read_csv('vehicles/vehicles.csv')

In [188]:
data.head(2)

Make              Model  Year  Engine Displacement  Cylinders  \
0  AM General  DJ Po Vehicle 2WD  1984                  2.5        4.0   
1  AM General   FJ8c Post Office  1984                  4.2        6.0   

      Transmission     Drivetrain                Vehicle Class Fuel Type  \
0  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   
1  Automatic 3-spd  2-Wheel Drive  Special Purpose Vehicle 2WD   Regular   

   Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0          19.388824        18           17            17   
1          25.354615        13           13            13   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550

## Simple Example: Starting with a numpy array. How can I filter the values of a list?

In [189]:
import numpy as np

In [190]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [191]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [192]:
new_list = []

for item in my_array:
    if item > 5:
        new_list.append(item)
        
new_list

[6, 7, 8, 9, 10]

In [196]:
my_array * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [195]:
my_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [201]:
my_array[ [False, False, False, False, False,  True,  True,  True,  True, True] ]

array([ 6,  7,  8,  9, 10])

In [208]:
mask = my_array < 7
mask

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [209]:
my_array[ mask ]

array([1, 2, 3, 4, 5, 6])

In [211]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
my_array[ my_array > 5 ]

array([ 6,  7,  8,  9, 10])

In [212]:
my_array[ my_array > 5 ] = 10

In [213]:
my_array

array([ 1,  2,  3,  4,  5, 10, 10, 10, 10, 10])

In [214]:
condition = my_array > 5 
condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [215]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [216]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
my_array[ condition ] = 123021

In [219]:
my_array

array([     1,      2,      3,      4,      5, 123021, 123021, 123021,
       123021, 123021])

In [222]:
x = np.random.randint(0,10, (3,6))
x

array([[8, 4, 8, 3, 4, 4],
       [7, 2, 5, 4, 5, 9],
       [9, 1, 6, 3, 0, 1]])

In [225]:
x[x > 3] = 1000

In [226]:
x

array([[1000, 1000, 1000,    3, 1000, 1000],
       [1000,    2, 1000, 1000, 1000, 1000],
       [1000,    1, 1000,    3,    0,    1]])

## Bitwise logical operators

In [228]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
# forma errada:
my_array > 5 and my_array < 8

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [234]:
my_array > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [235]:
my_array < 8

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [251]:
(my_array > 5) & (my_array < 8)

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [253]:
(my_array > 5) | (my_array < 8)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Bitwise and: &

Bitwise or: |

In [256]:
condition1 = my_array > 5
condition2 = my_array < 8

In [257]:
condition1 & condition2

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [259]:
my_array[ condition1 & condition2 ]

array([6, 7])

In [262]:
my_array[3:6]

array([4, 5, 6])

In [260]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [263]:
my_array[ condition1 & condition2 ] = 100

In [269]:
list(zip(condition1, condition2))

[(False, True),
 (False, True),
 (False, True),
 (False, True),
 (False, True),
 (True, True),
 (True, True),
 (True, False),
 (True, False),
 (True, False)]

In [264]:
my_array

array([  1,   2,   3,   4,   5, 100, 100,   8,   9,  10])

In [265]:
my_array[0] = 100

In [266]:
my_array

array([100,   2,   3,   4,   5, 100, 100,   8,   9,  10])

In [287]:
my_array > 3 & my_array < 8 # wrong
# my_array > (3 & my_array) < 8 # wrong
# (my_array > 3) & (my_array < 8) # correct

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Now in a dataframe

Let's find the rows in which the Cylinders values are exactly 6.

In [288]:
data['Cylinders']

0        4.0
1        6.0
2        4.0
3        6.0
4        6.0
        ... 
35947    3.0
35948    3.0
35949    3.0
35950    3.0
35951    3.0
Name: Cylinders, Length: 35952, dtype: float64

In [289]:
data['Cylinders'].unique()

array([ 4.,  6.,  5.,  8., 12., 10.,  2.,  3., 16.])

In [293]:
data['Cylinders']

0        4.0
1        6.0
2        4.0
3        6.0
4        6.0
        ... 
35947    3.0
35948    3.0
35949    3.0
35950    3.0
35951    3.0
Name: Cylinders, Length: 35952, dtype: float64

In [292]:
data['Cylinders'] == 6

0        False
1         True
2        False
3         True
4         True
         ...  
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Cylinders, Length: 35952, dtype: bool

In [299]:
mask = data['Cylinders'] == 6
mask

0        False
1         True
2        False
3         True
4         True
         ...  
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Cylinders, Length: 35952, dtype: bool

In [298]:
# acessando todas as linhas do meu dataframe
data.loc[:, ['Make','Model','Fuel Cost/Year','Cylinders']]

Make                Model  Fuel Cost/Year  Cylinders
0            AM General    DJ Po Vehicle 2WD            1950        4.0
1            AM General     FJ8c Post Office            2550        6.0
2            AM General  Post Office DJ5 2WD            2100        4.0
3            AM General  Post Office DJ8 2WD            2550        6.0
4      ASC Incorporated                  GNX            2550        6.0
...                 ...                  ...             ...        ...
35947             smart         fortwo coupe            1100        3.0
35948             smart         fortwo coupe            1100        3.0
35949             smart         fortwo coupe            1100        3.0
35950             smart         fortwo coupe            1100        3.0
35951             smart         fortwo coupe            1150        3.0

[35952 rows x 4 columns]

In [301]:
# acessando as linhas onde a máscara retorna True
data.loc[mask, ['Make','Model','Fuel Cost/Year','Cylinders']]

Make                Model  Fuel Cost/Year  Cylinders
1                 AM General     FJ8c Post Office            2550        6.0
3                 AM General  Post Office DJ8 2WD            2550        6.0
4           ASC Incorporated                  GNX            2550        6.0
7                      Acura          2.2CL/3.0CL            1650        6.0
10                     Acura          2.3CL/3.0CL            1650        6.0
...                      ...                  ...             ...        ...
35900  Wallace Environmental          Wetl 300 GE            3400        6.0
35901  Wallace Environmental          Wetl 300 SL            2700        6.0
35902  Wallace Environmental          Wetl 300 SL            2700        6.0
35903  Wallace Environmental          Wetl 300 TE            2700        6.0
35904  Wallace Environmental          Wetl 300 TE            2700        6.0

[12765 rows x 4 columns]

In [305]:
mask_cylinder = data['Cylinders'] == 6
mask_nome = data['Make'] == 'Acura'


data.loc[mask_cylinder & mask_nome, :]

Make        Model  Year  Engine Displacement  Cylinders  \
7    Acura  2.2CL/3.0CL  1997                  3.0        6.0   
10   Acura  2.3CL/3.0CL  1998                  3.0        6.0   
13   Acura  2.3CL/3.0CL  1999                  3.0        6.0   
16   Acura  2.5TL/3.2TL  1996                  3.2        6.0   
18   Acura  2.5TL/3.2TL  1997                  3.2        6.0   
..     ...          ...   ...                  ...        ...   
292  Acura          TSX  2014                  3.5        6.0   
303  Acura      ZDX 4WD  2010                  3.7        6.0   
304  Acura      ZDX 4WD  2011                  3.7        6.0   
305  Acura      ZDX 4WD  2012                  3.7        6.0   
306  Acura      ZDX 4WD  2013                  3.7        6.0   

        Transmission         Drivetrain                    Vehicle Class  \
7    Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
10   Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
13   Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
16   Automatic 4-spd  Front-Wheel Drive                     Compact Cars   
18   Automatic 4-spd  Front-Wheel Drive                     Compact Cars   
..               ...                ...                              ...   
292   Automatic (S5)  Front-Wheel Drive                     Compact Cars   
303   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
304   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
305   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
306   Automatic (S6)    All-Wheel Drive  Small Sport Utility Vehicle 4WD   

    Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
7     Regular          16.480500        18           26            20   
10    Regular          16.480500        17           26            20   
13    Regular          16.480500        17           26            20   
16    Premium          17.347895        17           22            19   
18    Premium          17.347895        17           22            19   
..        ...                ...       ...          ...           ...   
292   Premium          14.330870        19           28            23   
303   Premium          17.347895        16           23            19   
304   Premium          17.347895        16           23            19   
305   Premium          17.347895        16           23            19   
306   Premium          17.347895        16           23            19   

     CO2 Emission Grams/Mile  Fuel Cost/Year  
7                 444.350000            1650  
10                444.350000            1650  
13                444.350000            1650  
16                467.736842            2150  
18                467.736842            2150  
..                       ...             ...  
292               392.000000            1750  
303               467.736842            2150  
304               467.736842            2150  
305               467.736842            2150  
306               472.000000            2150  

[181 rows x 15 columns]

In [309]:
data.loc[mask_cylinder & mask_nome, 'Fuel Cost/Year'] = 1000 

In [312]:
data.head()

Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [316]:
data.loc[:, 'City MPG'].mean()

17.646139296840232

In [315]:
data.loc[mask_cylinder & mask_nome, 'City MPG'].mean()

17.281767955801104

In [ ]:
data.head(10)

In [321]:
mask_cylinder = data['Cylinders'] == 10

data.loc[mask_cylinder, 'City MPG'].mean()

11.65359477124183

In [322]:
data['Cylinders'].value_counts()

4.0     13494
6.0     12765
8.0      7998
5.0       723
12.0      562
3.0       201
10.0      153
2.0        48
16.0        8
Name: Cylinders, dtype: int64

## You can combine conditions

In [ ]:
data.loc[(data['Make'] == 'Ford') & (data['Cylinders'] == 6) & (data['Combined MPG'] < 18), :]

In [323]:
filtered = data.loc[(data['Make']=='Ford') &
                    (data['Cylinders']==6) &
                    (data['Combined MPG'] < 18)]

filtered

Make               Model  Year  Engine Displacement  Cylinders  \
11442  Ford        Aerostar Van  1986                  2.8        6.0   
11450  Ford        Aerostar Van  1988                  3.0        6.0   
11452  Ford        Aerostar Van  1989                  3.0        6.0   
11456  Ford        Aerostar Van  1990                  4.0        6.0   
11459  Ford        Aerostar Van  1991                  4.0        6.0   
...     ...                 ...   ...                  ...        ...   
14376  Ford  Windstar FWD Wagon  1997                  3.8        6.0   
14379  Ford  Windstar FWD Wagon  1999                  3.0        6.0   
14380  Ford  Windstar FWD Wagon  1999                  3.8        6.0   
14381  Ford  Windstar FWD Wagon  2000                  3.0        6.0   
14382  Ford  Windstar FWD Wagon  2000                  3.8        6.0   

          Transmission         Drivetrain             Vehicle Class Fuel Type  \
11442  Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
11450  Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
11452  Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
11456  Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
11459  Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
...                ...                ...                       ...       ...   
14376  Automatic 4-spd  Front-Wheel Drive  Special Purpose Vehicles   Regular   
14379  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
14380  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
14381  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
14382  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   

       Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
11442          19.388824        15           21            17   
11450          19.388824        15           20            17   
11452          19.388824        15           21            17   
11456          19.388824        15           20            17   
11459          19.388824        15           20            17   
...                  ...       ...          ...           ...   
14376          19.388824        15           21            17   
14379          19.388824        15           21            17   
14380          19.388824        15           21            17   
14381          19.388824        15           21            17   
14382          19.388824        15           21            17   

       CO2 Emission Grams/Mile  Fuel Cost/Year  
11442               522.764706            1950  
11450               522.764706            1950  
11452               522.764706            1950  
11456               522.764706            1950  
11459               522.764706            1950  
...                        ...             ...  
14376               522.764706            1950  
14379               522.764706            1950  
14380               522.764706            1950  
14381               522.764706            1950  
14382               522.764706            1950  

[680 rows x 15 columns]

In [325]:
filtered.reset_index()

index  Make               Model  Year  Engine Displacement  Cylinders  \
0    11442  Ford        Aerostar Van  1986                  2.8        6.0   
1    11450  Ford        Aerostar Van  1988                  3.0        6.0   
2    11452  Ford        Aerostar Van  1989                  3.0        6.0   
3    11456  Ford        Aerostar Van  1990                  4.0        6.0   
4    11459  Ford        Aerostar Van  1991                  4.0        6.0   
..     ...   ...                 ...   ...                  ...        ...   
675  14376  Ford  Windstar FWD Wagon  1997                  3.8        6.0   
676  14379  Ford  Windstar FWD Wagon  1999                  3.0        6.0   
677  14380  Ford  Windstar FWD Wagon  1999                  3.8        6.0   
678  14381  Ford  Windstar FWD Wagon  2000                  3.0        6.0   
679  14382  Ford  Windstar FWD Wagon  2000                  3.8        6.0   

        Transmission         Drivetrain             Vehicle Class Fuel Type  \
0    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
1    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
2    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
3    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
4    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
..               ...                ...                       ...       ...   
675  Automatic 4-spd  Front-Wheel Drive  Special Purpose Vehicles   Regular   
676  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
677  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
678  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
679  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   

     Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0            19.388824        15           21            17   
1            19.388824        15           20            17   
2            19.388824        15           21            17   
3            19.388824        15           20            17   
4            19.388824        15           20            17   
..                 ...       ...          ...           ...   
675          19.388824        15           21            17   
676          19.388824        15           21            17   
677          19.388824        15           21            17   
678          19.388824        15           21            17   
679          19.388824        15           21            17   

     CO2 Emission Grams/Mile  Fuel Cost/Year  
0                 522.764706            1950  
1                 522.764706            1950  
2                 522.764706            1950  
3                 522.764706            1950  
4                 522.764706            1950  
..                       ...             ...  
675               522.764706            1950  
676               522.764706            1950  
677               522.764706            1950  
678               522.764706            1950  
679               522.764706            1950  

[680 rows x 16 columns]

In [324]:
filtered.reset_index(drop=True)

Make               Model  Year  Engine Displacement  Cylinders  \
0    Ford        Aerostar Van  1986                  2.8        6.0   
1    Ford        Aerostar Van  1988                  3.0        6.0   
2    Ford        Aerostar Van  1989                  3.0        6.0   
3    Ford        Aerostar Van  1990                  4.0        6.0   
4    Ford        Aerostar Van  1991                  4.0        6.0   
..    ...                 ...   ...                  ...        ...   
675  Ford  Windstar FWD Wagon  1997                  3.8        6.0   
676  Ford  Windstar FWD Wagon  1999                  3.0        6.0   
677  Ford  Windstar FWD Wagon  1999                  3.8        6.0   
678  Ford  Windstar FWD Wagon  2000                  3.0        6.0   
679  Ford  Windstar FWD Wagon  2000                  3.8        6.0   

        Transmission         Drivetrain             Vehicle Class Fuel Type  \
0    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
1    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
2    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
3    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
4    Automatic 4-spd   Rear-Wheel Drive                      Vans   Regular   
..               ...                ...                       ...       ...   
675  Automatic 4-spd  Front-Wheel Drive  Special Purpose Vehicles   Regular   
676  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
677  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
678  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   
679  Automatic 4-spd  Front-Wheel Drive             Minivan - 2WD   Regular   

     Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0            19.388824        15           21            17   
1            19.388824        15           20            17   
2            19.388824        15           21            17   
3            19.388824        15           20            17   
4            19.388824        15           20            17   
..                 ...       ...          ...           ...   
675          19.388824        15           21            17   
676          19.388824        15           21            17   
677          19.388824        15           21            17   
678          19.388824        15           21            17   
679          19.388824        15           21            17   

     CO2 Emission Grams/Mile  Fuel Cost/Year  
0                 522.764706            1950  
1                 522.764706            1950  
2                 522.764706            1950  
3                 522.764706            1950  
4                 522.764706            1950  
..                       ...             ...  
675               522.764706            1950  
676               522.764706            1950  
677               522.764706            1950  
678               522.764706            1950  
679               522.764706            1950  

[680 rows x 15 columns]

## You can put the conditions in variables as well

In [326]:
condition1 = (data['Make']=='Ford')
condition2 = (data['Cylinders']==6)
condition3 = (data['Combined MPG'] < 18)


In [ ]:
data.loc[condition1 & condition2 & condition3, :]

## Another way to do the same thing.

* using the method `query`

The method `query` receives a string in which you can say your condition. Important things:
- `query` is a method of your dataframe
- the columns of the dataframe DOES NOT NEED to be inside quotation marks `"`, because it searchs for it in your dataframe
- the values you are trying to compare needs to be with the same type as it is in your dataframe (so if it is a string, it has to come within quotation marks, for example - so just be careful because you'll be using two quotation marks - the one for the query method, and the one for the string - and they should be alternated, i.e., if you've used "" for the query, the string should be within ''; if you've used '' for the query, the string should be within "")
- If your column has spaces, you have to call it using backticks like in the example below:


In [ ]:
data.query()

In [327]:
data.query('Make == "Acura" and Cylinders == 4')

Make        Model  Year  Engine Displacement  Cylinders  \
5    Acura  2.2CL/3.0CL  1997                  2.2        4.0   
6    Acura  2.2CL/3.0CL  1997                  2.2        4.0   
8    Acura  2.3CL/3.0CL  1998                  2.3        4.0   
9    Acura  2.3CL/3.0CL  1998                  2.3        4.0   
11   Acura  2.3CL/3.0CL  1999                  2.3        4.0   
..     ...          ...   ...                  ...        ...   
291  Acura          TSX  2014                  2.4        4.0   
293  Acura    TSX Wagon  2011                  2.4        4.0   
294  Acura    TSX Wagon  2012                  2.4        4.0   
295  Acura    TSX Wagon  2013                  2.4        4.0   
296  Acura    TSX Wagon  2014                  2.4        4.0   

        Transmission         Drivetrain         Vehicle Class Fuel Type  \
5    Automatic 4-spd  Front-Wheel Drive       Subcompact Cars   Regular   
6       Manual 5-spd  Front-Wheel Drive       Subcompact Cars   Regular   
8    Automatic 4-spd  Front-Wheel Drive       Subcompact Cars   Regular   
9       Manual 5-spd  Front-Wheel Drive       Subcompact Cars   Regular   
11   Automatic 4-spd  Front-Wheel Drive       Subcompact Cars   Regular   
..               ...                ...                   ...       ...   
291     Manual 6-spd  Front-Wheel Drive          Compact Cars   Premium   
293   Automatic (S5)  Front-Wheel Drive  Small Station Wagons   Premium   
294   Automatic (S5)  Front-Wheel Drive  Small Station Wagons   Premium   
295   Automatic (S5)  Front-Wheel Drive  Small Station Wagons   Premium   
296   Automatic (S5)  Front-Wheel Drive  Small Station Wagons   Premium   

     Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
5            14.982273        20           26            22   
6            13.733750        22           28            24   
8            14.982273        19           27            22   
9            13.733750        21           29            24   
11           14.982273        20           27            22   
..                 ...       ...          ...           ...   
291          13.733750        21           29            24   
293          13.184400        22           30            25   
294          13.184400        22           30            25   
295          13.184400        22           30            25   
296          13.184400        22           30            25   

     CO2 Emission Grams/Mile  Fuel Cost/Year  
5                 403.954545            1500  
6                 370.291667            1400  
8                 403.954545            1500  
9                 370.291667            1400  
11                403.954545            1500  
..                       ...             ...  
291               370.000000            1700  
293               355.480000            1600  
294               355.480000            1600  
295               358.000000            1600  
296               358.000000            1600  

[111 rows x 15 columns]

In [332]:
numero_cilindros = 6
data.query(f'Make == "Acura" and Cylinders == {numero_cilindros}')

Make        Model  Year  Engine Displacement  Cylinders  \
7    Acura  2.2CL/3.0CL  1997                  3.0        6.0   
10   Acura  2.3CL/3.0CL  1998                  3.0        6.0   
13   Acura  2.3CL/3.0CL  1999                  3.0        6.0   
16   Acura  2.5TL/3.2TL  1996                  3.2        6.0   
18   Acura  2.5TL/3.2TL  1997                  3.2        6.0   
..     ...          ...   ...                  ...        ...   
292  Acura          TSX  2014                  3.5        6.0   
303  Acura      ZDX 4WD  2010                  3.7        6.0   
304  Acura      ZDX 4WD  2011                  3.7        6.0   
305  Acura      ZDX 4WD  2012                  3.7        6.0   
306  Acura      ZDX 4WD  2013                  3.7        6.0   

        Transmission         Drivetrain                    Vehicle Class  \
7    Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
10   Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
13   Automatic 4-spd  Front-Wheel Drive                  Subcompact Cars   
16   Automatic 4-spd  Front-Wheel Drive                     Compact Cars   
18   Automatic 4-spd  Front-Wheel Drive                     Compact Cars   
..               ...                ...                              ...   
292   Automatic (S5)  Front-Wheel Drive                     Compact Cars   
303   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
304   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
305   Automatic (S6)    All-Wheel Drive      Sport Utility Vehicle - 4WD   
306   Automatic (S6)    All-Wheel Drive  Small Sport Utility Vehicle 4WD   

    Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
7     Regular          16.480500        18           26            20   
10    Regular          16.480500        17           26            20   
13    Regular          16.480500        17           26            20   
16    Premium          17.347895        17           22            19   
18    Premium          17.347895        17           22            19   
..        ...                ...       ...          ...           ...   
292   Premium          14.330870        19           28            23   
303   Premium          17.347895        16           23            19   
304   Premium          17.347895        16           23            19   
305   Premium          17.347895        16           23            19   
306   Premium          17.347895        16           23            19   

     CO2 Emission Grams/Mile  Fuel Cost/Year  
7                 444.350000            1000  
10                444.350000            1000  
13                444.350000            1000  
16                467.736842            1000  
18                467.736842            1000  
..                       ...             ...  
292               392.000000            1000  
303               467.736842            1000  
304               467.736842            1000  
305               467.736842            1000  
306               472.000000            1000  

[181 rows x 15 columns]

# Conditional Categories

In [337]:
data.loc[data['Transmission'].str.startswith('Auto'), :]

Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5   
1            AM General     FJ8c Post Office  1984                  4.2   
2            AM General  Post Office DJ5 2WD  1985                  2.5   
3            AM General  Post Office DJ8 2WD  1985                  4.2   
4      ASC Incorporated                  GNX  1987                  3.8   
...                 ...                  ...   ...                  ...   
35946             smart         fortwo coupe  2012                  1.0   
35947             smart         fortwo coupe  2013                  1.0   
35948             smart         fortwo coupe  2014                  1.0   
35949             smart         fortwo coupe  2015                  1.0   
35950             smart         fortwo coupe  2016                  0.9   

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive   
1            6.0  Automatic 3-spd     2-Wheel Drive   
2            4.0  Automatic 3-spd  Rear-Wheel Drive   
3            6.0  Automatic 3-spd  Rear-Wheel Drive   
4            6.0  Automatic 4-spd  Rear-Wheel Drive   
...          ...              ...               ...   
35946        3.0        Auto(AM5)  Rear-Wheel Drive   
35947        3.0        Auto(AM5)  Rear-Wheel Drive   
35948        3.0        Auto(AM5)  Rear-Wheel Drive   
35949        3.0        Auto(AM5)  Rear-Wheel Drive   
35950        3.0        Auto(AM6)  Rear-Wheel Drive   

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18   
1      Special Purpose Vehicle 2WD   Regular          25.354615        13   
2      Special Purpose Vehicle 2WD   Regular          20.600625        16   
3      Special Purpose Vehicle 2WD   Regular          25.354615        13   
4                     Midsize Cars   Premium          20.600625        14   
...                            ...       ...                ...       ...   
35946                  Two Seaters   Premium           9.155833        34   
35947                  Two Seaters   Premium           9.155833        34   
35948                  Two Seaters   Premium           9.155833        34   
35949                  Two Seaters   Premium           9.155833        34   
35950                  Two Seaters   Premium           9.155833        34   

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year  
0               17            17               522.764706            1950  
1               13            13               683.615385            2550  
2               17            16               555.437500            2100  
3               13            13               683.615385            2550  
4               21            16               555.437500            2550  
...            ...           ...                      ...             ...  
35946           38            36               246.861111            1100  
35947           38            36               244.000000            1100  
35948           38            36               243.000000            1100  
35949           38            36               244.000000            1100  
35950           39            36               246.000000            1100  

[24290 rows x 15 columns]

In [ ]:
data['Transmission'].str.startswith('A')

## I want to create a new column called TransType and call it "Automatic" if the value in Transmission starts with A, if it startswith M, I want to call it "Manual"

In [ ]:
data.loc[data['Transmission'].str.startswith('A'), 'TransType'] = 'Automatic'
data.loc[data['Transmission'].str.startswith('M'), 'TransType'] = 'Manual'