# Prova Itaú

## Clustering

<b>Questão 1) </b> Considerando os dados presentes no arquivo clus01.csv, execute o algoritmo K-Means com o posicionamento inicial dos centroides sendo: [1, 1, 1, 1], [-1, -1, -1, -1] e [1, -1, 1, -1]. Qual é o posicionamento final de cada centroide após 10 iterações?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
X = pd.read_csv('clus01.csv')
X

x0        x1        x2        x3
0    -0.450370 -2.244377 -0.499678 -1.163607
1     1.866159 -1.180407  1.898348 -1.072512
2    -1.731385  0.248746  0.177045 -1.618708
3    -2.211184 -0.066280  0.748191 -0.967796
4     0.739455  1.762124  2.319210  2.080270
...        ...       ...       ...       ...
2995  1.692026 -1.266796  1.422599 -0.018950
2996 -0.631424 -1.334187 -1.454879 -0.941082
2997  0.593961 -1.864158 -1.722376 -1.308181
2998  0.153214  1.419950  2.071526  1.853133
2999  0.960248 -1.623305  0.604997 -1.414892

[3000 rows x 4 columns]

In [3]:
guess_centers = np.array([[1, 1, 1, 1], [-1, -1, -1, -1], [1, -1, 1, -1]])
guess_centers

array([[ 1,  1,  1,  1],
       [-1, -1, -1, -1],
       [ 1, -1,  1, -1]])

In [4]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, init=guess_centers, max_iter=10, n_init=1)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True,
       init=array([[ 1,  1,  1,  1],
       [-1, -1, -1, -1],
       [ 1, -1,  1, -1]]),
       max_iter=10, n_clusters=3, n_init=1, n_jobs=None,
       precompute_distances='auto', random_state=None, tol=0.0001, verbose=0)

In [5]:
kmeans.cluster_centers_

array([[ 1.01800532,  1.02487255,  0.99716299,  1.02820958],
       [-1.00267381, -1.04904824, -1.03936684, -1.01122186],
       [ 1.01319407, -1.01061948,  0.97309582, -0.99640045]])

In [6]:
kmeans.predict(X)

array([1, 2, 1, ..., 1, 0, 2])

In [7]:
kmeans.inertia_

5766.298851554992

<b>Questão 2)</b> Assinale as alternativas com V ou F para Verdadeiro ou Falso respectivamente. Atente para o fato que uma questão errada anula uma certa. Em caso de dúvidas deixe em branco.

( ) O número mínimo de grupos no algoritmo K-Means é igual à raiz quadrada do número de elementos da base.

( ) Devido à inicialização aleatória, o resultado final do K-Means sempre será o mesmo independentemente do critério de convergência.

( ) O algoritmo K-Median é mais sensível a outliers do que os algoritmos K-Means, K-Mode e K-Medoid.

( ) O algoritmos Single-Linkage, Complete-Linkage e Average-Linkage são exemplos de algoritmos hierárquicos.

( ) Não é possível identificar outliers com algoritmos hierárquicos e, por este motivo, tais algoritmos requerem que os outliers sejam removidos numa etapa necessária de pré-processamento.

( ) Para conjuntos de dados com milhões de linhas é aconselhada a utilização de algoritmos hierárquicos em vez de algoritmos particionais pois aqueles calculam somente uma única matriz de distância.

( ) O Rand Index pode ser utilizado para mensurar a aderência entre o agrupamento obtido e um agrupamento de referência (por exemplo, dado por um especialista do domínio).

( ) O DBScan é um exemplo de algoritmo de agrupamento baseado em densidade.

( ) Para acelerar o tempo de processamento dos algoritmos de agrupamento baseados em densidade, pode-se calcular a distância de cada elemento para o centroide de cada um dos grupos.

( ) O número mínimo de variáveis necessárias para realizar um agrupamento é 1.

## Prova 2

<b>Questão 1)</b> Considerando os dados do arquivo agrupamento_Q1.csv, execute o algoritmo K-means com 10 iterações tendo como posiçãoo inicial dos centroides de cada cluster as K primeiras linhas do arquivo agrup_centroides_Q1.csv. Por exemplo, para executar o algoritmo com 3 clusters considere os centroides determinados pelas 3 primeiras linhas do arquivo.

Qual a quantidade ideal de clusters? Qual o posicionamento final dos centroides do caso ideal?

<b>Questão 2)</b> Assinale as alternativas com V ou F para Verdadeiro ou Falso respectivamente. Atente para o fato que uma questão errada anula uma certa. Em caso de dúvidas deixe em branco.

( ) O algoritmo K-means se baseia num processo iterativo que minimiza a soma das distâncias entre os centroides e os pontos dentro de cada agrupamento.

( ) O algoritmo K-means é pouco sensível a inicialização dos centroides e resulta sempre nos mesmos agrupamentos.

( ) Os centroides determinados pelo algoritmo K-means necessariamente pertencem ao conjunto de dados analisados

( ) O algoritmo K-median é mais sensível a outliers do que o algoritmo K-means.

( ) O algoritmo GMM (Gaussian Mixture Models) presume que os dados a serem agrupados provém de uma distribuição unimodal.

( ) Não é possível identificar outliers com algoritmos hierárquicos e, por este motivo, tais algoritmos requerem que os outliers sejam tratados em uma etapa necessária de pré-processamento.

( ) Algoritmos particionais são tipicamente mais eficientes computacionalmente do que algoritmos hierárquicos.

( ) Diferentemente do K-means, o DBScan é um algoritmo capaz de identificar agrupamentos com fomato de anéis concêntricos.

( ) Uma maneira eficaz de mensurar a semelhança entre dois vetores unitários de alta dimensão é calcular o produto interno entre os dois.